"""
Templates for the Code Generation Agent.
In production these feed an LLM; in local mode they guide template-based generation.
"""

CODING_PROMPT = """You are a Code Generation Agent. Implement the feature based on this blueprint.

BLUEPRINT:
{blueprint_json}

EXISTING FILE CONTENTS:
{existing_files}

Your task:
1. Create all new files listed in `files_to_create`
2. Modify all files listed in `files_to_modify`
3. Implement the API endpoints described
4. Add test cases for the new functionality

Write production-quality TypeScript/Node.js code.
Use the same patterns and style as the existing codebase.
Return the complete file contents for each file.
"""

GENERATED_HEADER = """/**
 * Auto-generated by SaaS Feature Factory - Code Generation Agent
 * Feature: {feature}
 * Generated: {timestamp}
 */
"""
